name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  RSH_CARGO_PROFILE: ci
  RSH_LOG_LEVEL: DEBUG
  CLIPPY_OPTIONS: "-D warnings -D clippy::unwrap_used"

jobs:
  fmt-clippy:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]
        feature: [default, dataframe, extra]
        include:
          - feature: default
            flags: ""
          - feature: dataframe
            flags: "--features=dataframe"
          - feature: extra
            flags: "--features=extra"
        exclude:
          - platform: windows-latest
            feature: dataframe
          - platform: macos-latest
            feature: dataframe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace ${{ matrix.flags }} --exclude rsh_plugin_* -- $CLIPPY_OPTIONS

      - name: Clippy of tests
        run: cargo clippy --tests --workspace ${{ matrix.flags }} --exclude rsh_plugin_* -- -D warnings

  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]
        feature: [default, dataframe, extra]
        include:
          - feature: default
            flags: ""
          - feature: dataframe
            flags: "--features=dataframe"
          - feature: extra
            flags: "--features=extra"
        exclude:
          - platform: windows-latest
            feature: dataframe
          - platform: macos-latest
            feature: dataframe
          - platform: windows-latest
            feature: extra
          - platform: macos-latest
            feature: extra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Tests
        run: cargo test --workspace --profile ci --exclude rsh_plugin_* ${{ matrix.flags }}

  std-lib-and-python-virtualenv:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-20.04, macos-latest, windows-latest]
        py:
          - py

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Install rsh
        run: cargo install --path . --locked --no-default-features

      - name: Standard library tests
        run: rsh -c 'use std testing; testing run-tests --path crates/rsh-std'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install virtualenv
        run: pip install virtualenv
        shell: bash

      - name: Test rsh in virtualenv
        run: rsh scripts/test_virtualenv.nu
        shell: bash

  plugins:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Clippy
        run: cargo clippy --package rsh_plugin_* ${{ matrix.flags }} -- $CLIPPY_OPTIONS

      - name: Tests
        run: cargo test --profile ci --package rsh_plugin_*
